### ISSUE TITLE
How can i install GLVis on my MacBook Air?

### ISSUE THREAD

**Issue by TongYunzhe** [GLVis/glvis#11]

**Comment by tzanio** [comment]
Hi @TongYunzhe,

You need to install XQuarz first, if that's not installed already. Their website is http://www.xquartz.org. This should install the OpenGL headers and you should be able to compile glvis following the instructions in http://glvis.org/building.

When you use glvis as a server, the first connection will take a while because it also has to start the XQuarz app. You can avoid the wait by manually starting XQuarz before glvis.

Hope this helps,
Tzanio

**Comment by TongYunzhe** [comment]
It's very helpful, now i can install GLVis on my MacBook Air, thank you so much. However, when i run the glvis and example 1, the terminal displayed "Can't connect to display! Initializing the visualization failed."

**Comment by tzanio** [comment]
It looks like we can't connect to the X window server. Did you try starting XQuarz manually first? Does it work from the command line, e.g. `glvis -m ../mfem/data/start.mesh` ?

**Comment by TongYunzhe** [comment]
it works now. thank you so much. I forgot to start XQuarz manually!~

**Comment by tzanio** [comment]
You are welcome. Let us know if you have any further questions.
