### ISSUE TITLE
Min coordinates in a XY plane don't appear

### ISSUE THREAD

**Issue by martemyev** [GLVis/glvis#12]
Hi All,

I'm visualizing the following solution [mesh_and_sol.zip](https://github.com/GLVis/glvis/files/149047/mesh_and_sol.zip)

When I make a 2D view (Shift+r) in the first XY plane the min coordinates of the domain don't show up. In all other planes they do.
![glvis_s16](https://cloud.githubusercontent.com/assets/2182432/13367528/cf12523c-dca8-11e5-97e7-5458d797226e.png)

I tried that with GLVis 3.1, but the same happens in GLVis 3.0.

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

This is a "feature" due to the way we position the minimal coordinates at the lowest left corner of the bounding box, where they are covered by the graph of the function.

We can consider changing this, but maybe an easier solution is just to enable a bit of transparency by pressing the 'k' key once as in the following:
![glvis_s01](https://cloud.githubusercontent.com/assets/1278247/13381782/50db802e-de19-11e5-9ebf-04e053660567.png)
Will that be sufficient for your needs?

Tzanio

**Comment by martemyev** [comment]
Ah, yes, that works for me.

Thank you!

Cheers,
Mikhail
