### ISSUE TITLE
Unable to visualize prism.msh

### ISSUE THREAD

**Issue by QiangWei-Wade** [GLVis/glvis#132]
Hello everyone,

I was trying to visualize a simple prism mesh extruded from trialgle 2D mesh by an [extrusion script](https://git.immc.ucl.ac.be/slim/demo-extrude) that uses gmsh. There's some discussion [here](https://gitlab.onelab.info/gmsh/gmsh/-/issues/1091#note_11868).

[square.msh.txt](https://github.com/GLVis/glvis/files/5711105/square.msh.txt)
[square_3d.msh.txt](https://github.com/GLVis/glvis/files/5711103/square_3d.msh.txt)
GMSH visualizes the extruded prism mesh just fine, but glvis couldn't visualize it properly and return errors.
```
MFEM Warning: Unsupported Gmsh element type.
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... in file: mesh/mesh_readers.cpp:1215
```

I tried to delete the triangle elements from square_3d.msh and this seemed to cause more problems
[square_3d_notri.msh.txt](https://github.com/GLVis/glvis/files/5711104/square_3d_notri.msh.txt)
```
MFEM abort: Gmsh file : no elements found
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... in file: mesh/mesh_readers.cpp:1286
```

Please advise what needs to be done to make it compatible with glvis and potentially mfem. Thank you!

Best wishes,
Wade

**Comment by bslazarov** [comment]
Hi Wade,

Could you please, use ParaView for visualization of prism elements until we investigate the issue. ParaView can visualize the prism elements without any problems. The only disadvantage is that the output has to be saved to a file before the visualization. 
Examples 5 and 9 demonstrate how to dump out the output into ParaView format. 

Best regards, Boyan

**Comment by bslazarov** [comment]
Hi Wade,

I just tried all of the supplied mesh files with mfem-4.2 and glvis. All of them work fine. Perhaps the problem is that you do not specify/mark all boundaries in square_3d.msh.txt. Glvis will show only the marked boundaries. If you want to visualize the elements press 'e' and then glvis will show the elements. The cuts though the mesh work fine as well. 

If you have older version of mfem anf glvis, please, replace them with the latest. 

Best regards, Boyan
