### ISSUE TITLE
Error in building GLVis in Fedora 35 (`SdlMainThread::setWindowIcon(SDL_Window*)')

### ISSUE THREAD

**Issue by paters06** [GLVis/glvis#210]
Good night GLVis team. I'm trying to install MFEM and GLVis in my laptop. When building GLVis, I find the following error:

```
/usr/bin/ld: lib/libglvis.a(sdl_main.o): en la función `SdlMainThread::setWindowIcon(SDL_Window*)':
sdl_main.cpp:(.text+0x634): referencia a `logo_rgba_len' sin definir
/usr/bin/ld: sdl_main.cpp:(.text+0x6ec): referencia a `logo_rgba' sin definir
collect2: error: ld devolvió el estado de salida 1
make: *** [makefile:276: glvis] Error 1
```
The error states that there is an undefined reference to `logo_rgba_len'. I have installed all the required dependencies so I don't know what to do.

Thank you very much for your attention.

PS: This is my first time submitting an issue so I apologize if I made some mistakes

**Comment by v-dobrev** [comment]
Hi @paters06,

It looks like the auto-generated file `share/logo.rgba.bin.cpp` was not properly generated. I suspect that the file is empty (its size is 0) and the reason is that the `xxd` command (that is used to generate this file from `share/logo.rgba`) is missing -- probably not installed on you machine for some reason.

It looks like `xxd` is part of the package `vim-common` on Fedora 35 (according to rpmfind: https://rpmfind.net/linux/rpm2html/search.php?query=%2Fusr%2Fbin%2Fxxd&submit=Search+...&system=fedora+35&arch=), so you should be able to install it with:
```console
sudo dnf install vim-common
```

**Comment by paters06** [comment]
Good night. Sorry for the delay. I had to work on windows during this week.

I have tried the installation of `vim-common` and the error is still there. What other suggestions do you have?

Thanks for your attention and response

**Comment by v-dobrev** [comment]
Can you check if the file `share/logo.rgba.bin.cpp` is empty or not? If it is empty, remove it and run `make` again.

**Comment by paters06** [comment]
`logo.rgba.bin.cpp` was empty. I followed your suggestion and it worked. Thank you very much
