### ISSUE TITLE
Compiling glvis

### ISSUE THREAD

**Issue by kmittal2** [GLVis/glvis#23]
Hi All,

I am new to using glvis and mfem so please bear with me as I am just getting started.. I am using a mac, and I have just gotten MFEM to build and run on my machine. I had to build mfem in a "build" folder inside the mfem directory using cmake and make. 
Now I am trying to get GLVis to build by specifying "make MFEM_DIR=../mfem/build -j" but I get the error "makefile:177: *** The MFEM library is not built.  Stop." 
I am not really sure what is causing this since I have confirmed by running MFEM examples that my MFEM build was successful. Any pointers on how I could get around this?

Thanks,
Ketan

**Comment by v-dobrev** [comment]
Hi Ketan,

The problem is that GLVis assumes that MFEM was build using the GNU make build system, not the CMake one. We are planning to add CMake build to GLVis that will work with the MFEM CMake build.

For now, I'd recommend building MFEM using the GNU make build system, e.g.:
```sh
cd mfem/build
make -f ../makefile config # [options] ...

# [optional]:
# copy ../config/defaults.mk to config/user.mk
#    cp -p ../config/defaults.mk config/user.mk
# and edit it as needed; then run 'make config' again:
#    make config

make -j 4
```

After that you should be able to build GLVis using the command you tried before.

Let us know if you encounter any further problems.

Thanks,
Veselin

**Comment by kmittal2** [comment]
Thanks Veselin, I have it running now!

Ketan
