### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by nicoguaro** [GLVis/glvis#26]
I followed the instructions given in the [website](http://glvis.org/building/). I also have
all the dependencies listed [here](https://github.com/GLVis/glvis/blob/master/INSTALL).
But I obtain the follwing error:

    cd lib; g++ -O3 -I/home/nguarinz/software/mfem-3.3 -DGLVIS_MULTISAMPLE=4 -DGLVIS_MS_LINEWIDTH=1.4 -I/usr/X11R6/include -DGLVIS_USE_LIBPNG -DGLVIS_USE_FREETYPE -I/usr/X11R6/include/freetype2 -I/usr/include/freetype2 -c aux_vis.cpp
    aux_vis.cpp:36:35: fatal error: fontconfig/fontconfig.h: No such file or directory
    compilation terminated.
    makefile:167: recipe for target 'lib/aux_vis.o' failed
    make: *** [lib/aux_vis.o] Error 1

I already have fontconfig installed, so I don't know what the problem is.

**Comment by tzanio** [comment]
Hi @nicoguaro, 

Do you know where `fontconfig/fontconfig.h` is installed in your system?

If it is not in `/usr/include` or `/usr/X11R6/include` you can modify the `FT_OPTS` variable in the `makefile` to add the directory where it can be found.

Hope that helps,
Tzanio

**Comment by nicoguaro** [comment]
The path in my system is

     /home/nguarinz/anaconda2/include/fontconfig/fontconfig.h

And I changed the line 134 of the makefile for

    FT_OPTS = -DGLVIS_USE_FREETYPE -I/usr/X11R6/include/freetype2\
 -I/usr/include/freetype2 -I/home/nguarinz/anaconda2/include/fontconfig

And obtain the following error when trying to compile

    usr/bin/ld: cannot find -lfontconfig
    collect2: error: ld returned 1 exit status
    makefile:175: recipe for target 'glvis' failed
    make: *** [glvis] Error 1

**Comment by tzanio** [comment]
Try adding `-L /home/nguarinz/anaconda2/lib` to `FT_LIBS`. 

You can also run without freetype (not recommended) by setting `USE_FREETYPE = NO`.

**Comment by nicoguaro** [comment]
I tried that and obtained much more errors. You can check the output in [this file](https://gist.githubusercontent.com/anonymous/28c7d7598701b9f4f18be2261d57fb4d/raw/d2677cfe9d8534db52e9674b500da21672a47ff6/glvis_compile.out)

**Comment by mlstowell** [comment]
It would seem that your version of fontconfig requires a library called libiconv.  This library is responsible for converting between different language or country specific text encodings.  If you can find libiconv on your system you can add its path in the same way that you added the path for libfontconfig.  If you don't have it, then you'll need to install this as well.

**Comment by v-dobrev** [comment]
You can also try running `pkg-config fontconfig --libs` -- that should give you all the options/libraries you need to add to `FT_LIBS`. You can do the same for freetype: `pkg-config freetype2 --libs`. This is mentioned in the comments in the `makefile`, see [here](https://github.com/GLVis/glvis/blob/master/makefile#L129-L136).

**Comment by v-dobrev** [comment]
One more thing: the output file you posted has a lot of messages about missing `std::...` - I see this type of messages if I use g++ (i.e. GCC) to build one library/source and then use clang++ when linking, or vice versa. In cases like that, run `make clean` in both the mfem and the glvis source directories and rebuild them making sure you use the same compiler for both.

Hope this helps,
Veselin

**Comment by nicoguaro** [comment]
I just did all that you suggested, and I have a different issue now

url: https://gist.github.com/anonymous/0003c0b019888d0462522a63fdc7b672

**Comment by mlstowell** [comment]
One small issue is that "-L/home/nguarinz/anaconda2/lib/libiconv.so" is invalid.  The "-L" option is used to add directories to the library search path during linking but you're passing a filename not a directory.  This directory is already in the search path because it was added so that libfontconfig could be found.  Rather than this "-L" option all you need is "-liconv" which tells the linker to look for a library called "libiconv.*" in the current library search path.

The other errors seem to indicate that g++ can't find its own libraries.  As Veselin pointed out this suggests that different C++ compilers are being used for different object files.  A closer look at the undefined symbols shows that they are part of the C++ 11 standard so it's also possible that the same compiler is being used with different standards.  Is is possible that some of your libraries were built with the C++11 standards activated but GLVis was not?  I believe the compiler option to look for is "-std=c++11".

**Comment by v-dobrev** [comment]
The only drawback when `USE_FREETYPE = NO` is that the fonts used by GLVis will be standard X11 fonts instead of the anti-aliased fonts that are used when `USE_FREETYPE = YES`.

If you want to try to get `USE_FREETYPE = YES` working, one more thing you can try (in addition to replacing `-L/home/nguarinz/anaconda2/lib/libiconv.so` with `-liconv` or `/home/nguarinz/anaconda2/lib/libiconv.so`) is to force `g++` to use the c++11 standard by adding the option `-std=c++11`, e.g. compile MFEM with
```sh
make CPPFLAGS=-std=c++11 serial -j
```
and then in the GLVis source directory:
```sh
make clean
make MFEM_DIR=../mfem-3.3 -j
```

By the way, what version of `g++` do you use? (You can check with `g++ -v`)

**Comment by nicoguaro** [comment]
I tried with all these options but it did not work.

The version of `g++` is 5.4. Thi is the output from `g++ -v`

    Using built-in specs.
    COLLECT_GCC=g++
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
