### ISSUE TITLE
Can I redistribute the binary?

### ISSUE THREAD

**Issue by CsatiZoltan** [GLVis/glvis#58]
I use the glvis executable in my Matlab code. My Matlab program is in a private repository on Bitbucket and it may later become public. However, I never intend my code to be used outside academia. Is it allowed to ship the compiled glvis with my code? It would simplify the usage.

I read the GNU license, I just want to make sure if I can do so.

**Comment by dalcinl** [comment]
So, basically, you are asking for **free legal advice** to folks who write and distribute free software under a free license, so you can benefit from your non-free code? :-)

**Comment by CsatiZoltan** [comment]
Well, it is currently just I who uses it, and when it reaches a certain maturity, I will change to a public repository with MIT license so it will as free as it can.

**Comment by dalcinl** [comment]
Well, as long as you keep it private and only for you, I think you can host the binary in your repo.

PS: I'm not a lawyer, just a user and casual contributor to this project, so take my words with a grain of salt.

**Comment by Follett2** [comment]
Thanks for your interest in glvis.  Here at Lawrence Livermore National Laboratory, we make software like glvis available to the public through open source licenses so it can be easily reused with clear legal rights and requirements.  But we don't provide legal advice or interpretations of the license - especially since reusing/redistributing /integrating codes often have facts unique to each situation.  Glvis is licensed under a modified LGPL v2.1 (see the license file in the repo).  Many public resources exist that explain the LGPL requirements - a notable source is the Free Software Foundation that authored the license (www.gnu.org).  If the license just absolutely does not work for your situation, please send us an email with your specific facts to softwarelicensing@lists.llnl.gov - ie "If you wish to incorporate parts of the Library into other free programs whose distribution conditions are incompatible with these, write to the author to ask for permission."

**Comment by CsatiZoltan** [comment]
@Follett2 Thank you. When my toolbox becomes public, I may change its license to fit LGPL v2.1 (however I use other external programs too, which have different licenses, so it will be a bit of challenge to fulfil all). I will then write an e-mail to the link you provided.
