### ISSUE TITLE
Using a socket to update the plot caption

### ISSUE THREAD

**Issue by Jannertje** [GLVis/glvis#72]
Heya,

I'm using GLVis + MFEM for my research, and have an application that is continuously pushing new solutions to GLVis through a socket, like you are doing in your MFEM example code.

I found in your GLVis CHANGELOG file a reference to an undocumented socket command `plot_caption`, which I've been trying to get to work.

My current code is (somewhat like) the one from your examples:
```c++
char vishost[] = "localhost";
int  visport   = 19916;
socketstream sol_sock(vishost, visport);
sol_sock.precision(8);
sol_sock << "solution" << endl << *mesh << solution << flush;
```
How do I push a new plot_caption? I tried a couple of things, like
```c++
sol_sock << "solution" << endl << *mesh << solution << flush;
sol_sock << "plot_caption" << endl << "heya" << flush;


sol_sock << "solution" << endl << *mesh << solution << flush;
sol_sock << "plot_caption" << endl << "heya" << endl << flush;


sol_sock << "solution" << endl << *mesh << solution << endl
         << "plot_caption" << endl << "heya" << endl << flush;
```
but these all mess up GLVis more or less completely, in the sense that it tries to read the *next* mesh data into the caption.

Is there something I am missing?

**Comment by v-dobrev** [comment]
Hi @Jannertje,

The plot caption itself has to be quoted -- the first non-whitespace symbol after `plot_cation` is treated as the quoting symbol. For example, in you code you can single quotes: instead of `"heya"` use `"'heya'"`. This is done so that you can have almost any combination of symbols in the caption while keeping the parsing code in GLVis simple.

Hope this helps,
Veselin

**Comment by tzanio** [comment]
See also https://github.com/mfem/mfem/blob/master/examples/ex17.cpp#L297-L303
